<?php
/**
 * @file
 * droop_form.module
 */

/**
 * Implements hook_forms().
 */
function droop_form_forms($form_id, $args) {
  return droop_di_get_service('droop_form.manager')->getFormCallbacks($form_id, $args);
}

/**
 * Procedural callback for forms that use a FormBuilderInterface class.
 *
 * @param string $form_id
 *   This can be either
 *    - A form id defined by a form builder FormBuilderInterface::formId().
 *    - A class name implementing FormBuilderInterface.
 * @param array $form
 * @param array $form_state
 *
 * @see FormBuilderInterface
 *
 * @return array
 */
function droop_form_load_form($form, &$form_state, $form_id) {
  $args = array_slice(func_get_args(), 3);

  return call_user_func_array(
    [droop_di_get_service('droop_form.manager'), 'getForm'],
    array_merge([$form_id, $form, &$form_state], $args)
  );
}

/**
 * Implements hook_form_alter().
 */
function droop_form_form_alter(&$form, &$form_state, $form_id) {
  droop_di_get_service('droop_form.manager')->alterForm($form, $form_state, $form_id);
}
