<?php

use Drupal\droop_menu\MenuRouteForwarder;
use Drupal\droop_menu\MenuRouteModel;

/**
 * Implements hook_menu().
 */
function droop_menu_menu() {
  /** @var MenuRouteModel $items */
  $items = droop_di_get_service('droop_menu.manager')->getAllMenuRoutes();
  return $items->getItems();
}

/**
 * Implements hook_menu_alter().
 */
function droop_menu_menu_alter(&$items) {
  $model = new MenuRouteModel($items);
  droop_di_get_service('droop_menu.manager')->alterMenuRoutes($model);
  return $items;
}

/**
 * Implements hook_permission().
 */
function droop_menu_permission() {
  return droop_di_get_service('droop_menu.manager')->getPermissions();
}

/**
 * Menu router for controller objects.
 *
 * Either a page callback, or an access callback. Returns FALSE (not found / no
 * access) by default.
 *
 * @param \Drupal\droop_menu\MenuRouteForwarder $route
 *
 * @return bool|mixed
 */
function droop_menu__menu_router($route) {
  if (!$route instanceof MenuRouteForwarder) {
    return FALSE;
  }

  try {
    $controller = droop_di_get_service('droop_menu.plugin_loader')->getPlugin($route->getPlugin());
  }
  catch (Exception $e) {
    droop_di_get_service('system.logger')->log($e->getMessage());
    return FALSE;
  }

  $args = array_slice(func_get_args(), 1);
  return call_user_func_array([$controller, str_replace(':', '', $route->getMethod())], $args);
}
